# Generated by Django 5.0.1 on 2024-01-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_remove_patient_address_remove_patient_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='wredommend',
            new_name='wrecommend',
        ),
        migrations.AddField(
            model_name='patient',
            name='healthissue',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospitalization_condition',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
