# Generated by Django 5.0.1 on 2024-01-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_rename_wredommend_patient_wrecommend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
