# Generated by Django 5.0.1 on 2024-01-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_alter_patient_drecommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='baseapp.doctor'),
        ),
    ]
