# Generated by Django 5.0.1 on 2024-01-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_alter_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(default="Don't know", max_length=20),
        ),
    ]
