# Generated by Django 5.0.1 on 2024-01-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_donor_bloodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='amount',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
