# Generated by Django 5.0.1 on 2024-01-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_donor_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='healthissue',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospitalization_condition',
            field=models.TextField(default=None),
        ),
    ]
