# Generated by Django 5.0.1 on 2024-01-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0012_alter_patient_healthissue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='picture',
            field=models.ImageField(max_length=75, null=True, upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='drecommend',
            field=models.ImageField(max_length=50, null=True, upload_to='drecommend'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='wrecommend',
            field=models.ImageField(max_length=50, null=True, upload_to='wrecommend'),
        ),
    ]
